repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-added-large-files
    args: [--maxkb=1024]
  - id: check-symlinks
  - id: mixed-line-ending
- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
  - id: black

- repo: https://github.com/PyCQA/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ["--config=setup.cfg", "--ignore=E501,W503"]

- repo: https://github.com/timothycrosley/isort
  rev: 5.10.1
  hooks:
  - id: isort
    # Required for isort to be configured via pyproject.toml
    additional_dependencies: ["toml"]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.961
  hooks:
    - id: mypy
      additional_dependencies: ["types-all"]
